---
title: "Midterm 2: Data Manipulation"
author: "Susannah, Finn, Khanh"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(lubridate)
library(ggplot2)
```

# Data

```{r}
member <- read.csv("https://collinn.github.io/data/member.csv")
claims <- read.csv("https://collinn.github.io/data/claims.csv")
```

Our study is restricted to only those women who were at least 18 years old and younger than 41 (that is 40 and 11 months is fine, 41 years and 0 months is not) at the time of delivery.

```{r}
# Finn:
# Attempting to use lubridate to filter only patients from are 18 years old and younger than 41. 


```

```{r}
# Attempting to find only claims which are births 
birth_claims <- claims %>% 
  mutate(delivery_type = case_when(
    ICD %in% c("O80") ~ "Vaginal",
    ICD %in% c("O82") ~ "Cesarean",
    TRUE ~ NA_character_
  )) %>%
  mutate(migraine_status = ifelse(ICD %in% c("G43.4"), 1, 0)) %>%
  mutate(mental_health_diagnosis = case_when(
    ICD %in% c("F41.8") ~ "Anxiety",
    ICD %in% c("F32.3") ~ "Depression",
    TRUE ~ NA_character_
  ))

# Once we have the birth claims, we can join with members to filter out any
# members who got opioids that did not give birth


```

```{r}
# convert dates and calculate age
member <- member %>%
  mutate(DoB = ymd(DoB),
         age_at_delivery = floor(interval(DoB, ymd(paste(year, month, "01", sep="-"))) / years(1)))

# apply age filter
member <- member %>% filter(age_at_delivery >= 18 & age_at_delivery < 41)
head(member)
```


```{r}
#join birth claims to member
joined_claims <- inner_join(x = birth_claims, y = member, by = "id")

join_claims <- joined_claims %>%
  rename(Date_Delivery=date)
```

```{r}
# For insurance claims: similar to Khanh's mutation, create a binary variable
# for whether individuals have had events happen to them each claim.
claims_history <- claims %>% 
   mutate(gave_birth = ifelse(ICD %in% c("O80", "O82"), 1, 0)) %>%
   mutate(migraine_status = ifelse(ICD %in% c("G43.4"), 1, 0)) %>%
   mutate(mental_health_diagnosis = ifelse(ICD %in% c("F41.8", "F32.3"), 1, 0)) %>%
   mutate(opioid_prescription = ifelse(ICD %in% c("J0745"), 1, 0))

# Summarize individual patients to see if they fit any of our criteria of interest:
# gave birth, had migraine, had mental health issues, or had opioids prescribed. 
# Group by id for a single patient. 
patient_summaries <- claims_history %>% 
  group_by(id) %>%
  summarize(gave_birth = ifelse(max(gave_birth > 0), "Yes", "No"),
            had_migraine = ifelse(max(migraine_status > 0), "Yes", "No"),
            mental_health_diagnosis = ifelse(max(mental_health_diagnosis > 0), "Yes", "No"),
            opioid_prescription = ifelse(max(opioid_prescription > 0), "Yes", "No"))

# We may be able to remove patients who do not fit any of our criteria.
# However... this is a limited analysis, does not consider timeframe.
# Might be good for chopping down observations.

# Idea: remove individuals of disinterest from patient_summaries, and then join
# by matching patient IDs which remain.
```

```{r}
#I added to Finn's code so it was easier to see type of birth
claims_history <- claims %>% 
   mutate(gave_birth = ifelse(ICD %in% c("O80", "O82"), 1, 0)) %>%
   mutate(vaginal = ifelse(ICD %in% "O80", 1, 0)) %>%
   mutate(Csection = ifelse(ICD %in% "O82", 1, 0)) %>%
   mutate(migraine_status = ifelse(ICD %in% c("G43.4"), 1, 0)) %>%
   mutate(mental_health_diagnosis = ifelse(ICD %in% c("F41.8", "F32.3"), 1, 0)) %>%
   mutate(opioid_prescription = ifelse(ICD %in% c("J0745"), 1, 0))
```

```{r}
#I also added type of birth to this code
patient_summaries <- claims_history %>% 
  group_by(id) %>%
  summarize(gave_birth = ifelse(max(gave_birth > 0), "Yes", "No"),
            vaginal = ifelse(max(vaginal > 0), "Yes", "No"),
            Csection = ifelse(max(Csection > 0), "Yes", "No"),
            had_migraine = ifelse(max(migraine_status > 0), "Yes", "No"),
            mental_health_diagnosis = ifelse(max(mental_health_diagnosis > 0), "Yes", "No"),
            opioid_prescription = ifelse(max(opioid_prescription > 0), "Yes", "No"))
```

```{r}
#the way we originally calculated age at delivery was changing depending on the insurance year
#here's a new way I figured out
member_age <- join_claims %>%
  mutate(Age_Delivery=ymd(Date_Delivery)-ymd(DoB)) %>%
  mutate(Age_Delivery=Age_Delivery/365) %>%
  mutate(Age_Delivery=as.integer(Age_Delivery)) %>%
  filter(Age_Delivery >= 18 & Age_Delivery < 41)
```

```{r}
#data set of only people who gave birth, their medical claims, and months insured
join_births <- inner_join(x=member_age, y=patient_summaries, by = "id")
#this has the right ages since I filtered it, but we still need to figure out how long they were insured
```

```{r}
#counts how many months patient insured since each month is one row
insured_time <- member %>%
  group_by(id) %>%
  summarize(insured_length=n())

#join insured_length to main dataset
join_insurance <- inner_join(x=join_births, y=insured_time, by = "id") %>%
  filter(Date_Delivery >= "2017-09-01")#because sept 1st earliest delivery date we can gurantee they were insured 9 months before if insured starting on jan 1st
#there are 5,981 individual ids in this set
```

```{r}

join_births <- join_births %>%
  mutate(
    insurance_date = as.Date(paste(year, month, "01", sep = "-")),
    delivery_date = as.Date(Date_Delivery),  # Ensure Delivery_Date is in Date format
    required_start = floor_date(delivery_date %m-% months(9), "month"),  # 9 months before
    required_end = ceiling_date(delivery_date %m+% months(3), "month") - days(1)  # 3 months after end of delivery month
  ) %>%
  group_by(id) %>%
  mutate(
    insurance_start_date = min(insurance_date, na.rm = TRUE),
    insurance_end_date = max(insurance_date, na.rm = TRUE),
    insured_for_entire_period = insurance_start_date <= required_start & 
                                insurance_end_date >= required_end
  ) %>%
  ungroup() %>%
  filter(insured_for_entire_period) %>%  # Keep only those meeting criteria
  select(-c(insurance_date, month, year, required_start, required_end, insured_for_entire_period)) %>%
  drop_na(delivery_type)

```



```{r}
# Finn 6005 observations. We need to cut this down? 
join_insurance_late <- inner_join(x=join_births, y=insured_time, by = "id") %>%
  filter(Date_Delivery >= "2017-09-01",
         Date_Delivery <= "2018-09-01")

patient_final_summaries <- join_insurance_late %>% 
  group_by(id) %>%
  summarize(gave_birth = ifelse(max(gave_birth > 0), "Yes", "No"),
            vaginal = ifelse(max(vaginal > 0), "Yes", "No"),
            Csection = ifelse(max(Csection > 0), "Yes", "No"),
            migraine_status = ifelse(max(migraine_status > 0), "Yes", "No"),
            mental_health_diagnosis.x = ifelse(max(mental_health_diagnosis.y > 0), "Yes", "No"),
            opioid_prescription = ifelse(max(opioid_prescription > 0), "Yes", "No"),
            age_at_delivery = max(age_at_delivery)) %>%
  subset(gave_birth %in% c("Yes"))


# Idea: mutate a data set into only birth claims, pull the date they gave births, and join this with insured_time? new variable "date_gave_birth" which can be our grounds for filtering

# We can have 4237 - 4249
```



```{r}
# Individual patient claims for births.
gave_birth_dates <- claims %>%
  filter(ICD %in% c("O80", "O82")) %>%
  group_by(id) %>%
  summarise(gave_birth_date = min(date))
```

```{r}
#filtering by if they gave birth, then the date connected should be the delivery date
claim_filter <- claims %>%
  filter(ICD %in% c("O80", "O82")) %>%
  select(!CPT, ICD)


#joins the insurance start and ends with the delivery dates
join_dates_claims <- inner_join(x=claim_filter, y=start_end_dates, by="id") %>%
  select(!ICD)
```
